# models: [UNet, DeepLabV3]
models: [DeepLabV3]
losses: [CELoss, DACLoss, SCELoss, FocalLoss, SFLoss]

optimizers:
  [
    {
      "name": "SGD",
      "args":
        { "lr": !!float 1e-3, "momentum": 0.9, "weight_decay": !!float 1e-2 },
    },
    { "name": "AdamW", "args": { "lr": !!float 1e-3 } },
  ]

# datasets
datasets:
  [
    {
      "name": "cadis",
      "image_size": [270, 480],
      "batch_size": 64,
      "setup": 3,
      "max_epochs": 50,
      "transforms": [],
    },
    {
      "name": "ade20k",
      "image_size": [480, 512],
      "batch_size": 16,
      "setup": 2,
      "max_epochs": 30,
    },
  ]

seed: 13
devices: 3
