seed: 13
max_epochs: 30
devices: 3

# dataset: ade20k
# image_size: [480, 512]
# batch_size: 16
# setup: 2

dataset: cadis
image_size: [270, 480]
batch_size: 64
setup: 1
transforms: []
# transforms: ["original", "blur", "elastic", "jitter", "equalize", "flip"]
# transforms: ["original", "blur", "elastic", "flip"]

model:
  module: models
  # name: UNet
  name: DeepLabV3
  args:
    loss:
      module: losses
      name: CELoss
      args: {}
      # name: DACLoss
      # args:
      #   max_epochs: 30
      # name: SCELoss
      # args: {}
      # name: FocalLoss
      # args: {}
      # name: SFLoss
      # args: {}
    optimizer:
      module: torch.optim
      name: AdamW
      args:
        lr: !!float 1e-3
