seed: 13
dataset: ade20k
# dataset: cadis
# image_size: !!python/tuple [480, 512]
image_size: [480, 512]
# image_size: [270, 480]
# transforms: ["original", "blur", "elastic", "jitter", "equalize", "flip"]
transforms: ["original", "blur", "elastic", "flip"]
batch_size: 16

model:
  module: models
  name: UNet
  args:
    loss:
      module: losses
      name: CELoss
      args: {}
      # name: DACLoss
      # args:
      #   max_epochs: 30
      # name: SCELoss
      # args: {}
      # name: FocalLoss
      # args: {}
      # name: SFLoss
      # args: {}
    optimizer:
      module: torch.optim
      name: AdamW
      args:
        lr: !!float 1e-4

max_epochs: 30
devices: 3
