program: ads_sweep.py
project: playground
name: ads dsad
method: grid
metric:
  goal: maximize
  name: test/miou_final
parameters:
  warmup_epochs:
    # min: 10
    # max: 20
    # values: [10, 15, 20]
    value: 10

  alpha_final:
    # min: 1.0
    # max: 5.0
    values: [1, 2, 3, 4, 5]
  gamma:
    values: [1, 1.5, 2]
    # min: 1.0
    # max: 5.0
  window_size:
    # values: [4, 8, 16, 32]
    value: 16
  noise_level:
    value: 5
