program: asce_sweep.py
project: thesis
name: asce parameters-cadis-unet
method: random
metric:
  goal: maximize
  name: test/mIoU
parameters:
  # warmup_rate:
  # min: 0.05
  # max: 0.25
  # gamma:
  # min: 1
  # max: 5
  alpha:
    min: 0.5
    max: 1.0
  beta:
    min: 0.1
    max: 1.0
  lr:
    min: 0.001
    max: 0.1
