program: dac_sweep.py
project: thesis
name: dac parameters-cadis-unet
method: bayes
metric:
  goal: maximize
  name: test/mIoU
parameters:
  warmup_rate:
    min: 0.05
    max: 0.3
  alpha_init_factor:
    values: [32, 64, 128]
  alpha_final:
    min: 0.5
    max: 5.0
  mu:
    min: 0.01
    max: 0.5
