program: dac_sweep.py
project: thesis
name: dac parameters-cadis-unet
method: random
metric:
  goal: maximize
  name: test/mIoU
parameters:
  warmup_rate:
    values: [0.05, 0.1, 0.15, 0.2]
  alpha_init_factor:
    values: [32, 64, 128]
  alpha_final:
    min: 0.5
    max: 5.0
  mu:
    min: 0.01
    max: 0.5
