program: dac_sweep.py
project: DAC Segmentation
name: DAC parameters
method: bayes
metric:
  goal: maximize
  name: test/mIoU
parameters:
  model:
    value: UNet
  dataset:
    value: cadis
  lr:
    min: 0.001
    max: 0.1
  warmup_rate:
    values: [0.1, 0.2, 0.3]
  alpha_init_factor:
    values: [32, 64, 128]
  alpha_final:
    min: 0.1
    max: 2.0
  mu:
    min: 0.01
    max: 0.1
