program: dac_sweep.py
project: xdac
name: dac
method: random
metric:
  goal: maximize
  name: test/mIoU
parameters:
  warmup_epochs:
    min: 5
    max: 20
  alpha_final:
    min: 1.0
    max: 3.0
  batch_size:
    values: [64, 128, 196]
