program: dac_sweep.py
project: playground
name: dac cadis
method: grid
metric:
  goal: maximize
  name: valid/miou_final
parameters:
  warmup_epochs:
    # min: 10
    # max: 20
    value: 10
  alpha_final:
    # min: 1.0
    # max: 5.0
    values: [1, 2, 3, 4, 5]
  noise_level:
    value: 5
