program: gce_sweep.py
project: playground
name: gce cadis
method: grid
metric:
  goal: maximize
  name: test/miou_final
parameters:
  q:
    # min: 0.001
    # max: 1.0
    # values: [0.1, 0.2, 0.3, 0.4, 0.5]
    values: [0.6, 0.7]
  dataset:
    value: dsad
  noise_level:
    values: [3, 5]
