program: gce_sweep.py
project: thesis
name: gce-cadis-unet
method: grid
metric:
  goal: maximize
  name: valid/mIoU
parameters:
  q:
    # min: 0.01
    # max: 0.5
    values: [0.01, 0.05, 0.1, 0.2, 0.5]
  noise_level:
    values: [1, 2, 3, 4, 5]
