program: idac_sweep.py
project: thesis
# name: idac parameters-cadis-unet
name: idac alpha noise-cadis-unet
method: grid
metric:
  goal: maximize
  name: test/mIoU
parameters:
  # warmup_rate:
  #   min: 0.05
  #   max: 0.3
  # alpha:
  #   min: 1
  #   max: 20
  scale:
    values: [20, 30, 50, 70, 100, 150, 200]
  noise_level:
    values: [1, 2, 3, 4, 5]
