program: idac_sweep.py
project: thesis
name: idac parameters-cadis-unet
method: grid
metric:
  goal: maximize
  name: test/mIoU
parameters:
  warmup_rate:
    values: [0.05, 0.1, 0.15, 0.2]
  alpha:
    values: [1, 5, 10, 20]
