program: idac_sweep.py
project: playground
name: idac cadis
method: grid
metric:
  goal: maximize
  name: test/miou_final
parameters:
  warmup_epochs:
    # min: 5
    # max: 25
    # values: [10, 12, 15, 18, 20]
    value: 10
  alpha:
    # min: 1.0
    # max: 10.0
    values: [1, 2, 3, 5, 10, 20]
  # scale:
  noise_level:
    value: 5
  #   values: [1, 2, 3, 4, 5]
