program: sce_sweep.py
project: playground
name: sce cadis
method: grid
metric:
  goal: maximize
  name: test/miou_final
parameters:
  alpha:
    # min: 0.01
    # max: 3.0
    values: [0.5, 1.0, 1.5, 2.0]
  beta:
    # min: 0.01
    # max: 3.0
    values: [0.5, 1.0, 1.5, 2.0]
    dataset:
    value: cadis
  noise_level:
    values: [3, 5]
