program: sce_sweep.py
project: thesis
name: sce parameters-cadis-unet
method: random
metric:
  goal: maximize
  name: test/mIoU
parameters:
  alpha:
    min: 0.1
    max: 1.0
  beta:
    min: 0.5
    max: 2.0
