program: sce_sweep.py
project: thesis
name: sce parameters noise-cadis-unet
method: bayes
metric:
  goal: maximize
  name: valid/mIoU
parameters:
  alpha:
    min: 0.1
    max: 1.0
  A:
    min: -10
    max: -2
