program: sweep.py
project: thesis
name: dsad samples
method: grid
metric:
  goal: maximize
  name: test/miou_final
parameters:
  model:
    # value: deeplabv3+
    value: unet
  dataset:
    # value: cadis
    value: dsad
  noise_level:
    # values: [0, 1, 2, 3, 4, 5]
    value: 5
  loss:
    values:
      [
        GACLoss,
        GCELoss,
        SACLoss,
        SCELoss,
        ADSLoss,
        DiceLoss,
        DACLoss,
        IDACLoss,
        CELoss,
      ]
    # values: [DiceLoss, CELoss]
    # values: [CELoss, DiceLoss, DACLoss, IDACLoss, ADSLoss]
  seed:
    # values: [1, 2, 3, 4, 5]
    value: 1
