program: sweep.py
project: thesis
name: cadis full
method: grid
metric:
  goal: maximize
  name: test/miou_final
parameters:
  model:
    # values: [UNet, DeepLabV3Plus, FPN]
    value: UNet
  dataset:
    value: { "name": "cadis", "batch_size": 128 }
    # value: { "name": "dsad", "batch_size": 50 }
  noise_level:
    values: [0, 1, 2, 3, 4, 5]
    # value: 5
  loss:
    values:
      [
        GACLoss,
        GCELoss,
        SACLoss,
        SCELoss,
        ADSLoss,
        DiceLoss,
        DACLoss,
        IDACLoss,
        CELoss,
      ]
    # values: [DiceLoss, CELoss]
    # values: [CELoss, DiceLoss, DACLoss, IDACLoss, ADSLoss]
  seed:
    values: [1, 2, 3, 4, 5]
    # value: 1
