program: sweep.py
project: thesis
name: main-cadis-5
# name: abstention post-optimization
method: grid
metric:
  goal: maximize
  name: test/mIoU
parameters:
  model:
    # values: [UNet, DeepLabV3Plus, FPN]
    value: UNet
  dataset:
    values: [
        { "name": "cadis", "batch_size": 128, "setup": 1, "augmentations": {} },
        # {
        #   "name": "dsad",
        #   "batch_size": 64,
        #   "augmentations": { "normalized": True, "rotated": True },
        # },
      ]
  noise_level:
    values: [0, 1, 2, 3, 4, 5]
    # values: [1, 5]
    # value: 5
  loss:
    # values: [ADSLoss, DiceLoss, DACLoss, IDACLoss, CELoss, SCELoss, GCELoss]
    # values: [DiceLoss, CELoss]
    values: [ADSLoss, DACLoss, IDACLoss, DiceLoss, CELoss]
  seed:
    values: [1, 2, 3, 4, 5]
    # value: 1
