program: sweep.py
project: thesis
name: main
method: grid
metric:
  goal: maximize
  name: test/mIoU
parameters:
  model:
    # values: [UNet, DeepLabV3Plus, FPN]
    value: UNet
  dataset:
    values:
      [
        { "name": "cadis", "batch_size": 128, "setup": 1, "augmentations": {} },
        { "name": "dsad", "batch_size": 64, "augmentations": {} },
      ]
  # "flipped": True,
  # "gaussian": True,
  # "normalized": True,
  # "rotated": True,
  noise_level:
    values: [1, 2, 3, 4, 5]
    # value: 5
  loss:
    values: [CELoss, DACLoss, IDACLoss, SCELoss, ASCELoss]
