program: sweep.py
project: thesis
name: main-unet-100 epochs
method: grid
metric:
  goal: maximize
  name: test/mIoU
parameters:
  model:
    # values: [UNet, DeepLabV3Plus, FPN]
    value: UNet
  dataset:
    values:
      [
        { "name": "cadis", "batch_size": 142, "setup": 1, "augmentations": {} },
        {
          "name": "dsad",
          "batch_size": 120,
          "augmentations": { "normalized": True, "rotated": True },
        },
      ]
  noise_level:
    values: [1, 2, 3, 4, 5]
    # value: 5
  loss:
    values: [CELoss, GCELoss, SCELoss, DACLoss, IDACLoss]
